// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: weight.proto

package weight_pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeightModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightModel) Reset() {
	*x = WeightModel{}
	mi := &file_weight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightModel) ProtoMessage() {}

func (x *WeightModel) ProtoReflect() protoreflect.Message {
	mi := &file_weight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightModel.ProtoReflect.Descriptor instead.
func (*WeightModel) Descriptor() ([]byte, []int) {
	return file_weight_proto_rawDescGZIP(), []int{0}
}

func (x *WeightModel) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_weight_proto protoreflect.FileDescriptor

const file_weight_proto_rawDesc = "" +
	"\n" +
	"\fweight.proto\x12\x06weight\"%\n" +
	"\vWeightModel\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06valuesB\rZ\v./weight_pbb\x06proto3"

var (
	file_weight_proto_rawDescOnce sync.Once
	file_weight_proto_rawDescData []byte
)

func file_weight_proto_rawDescGZIP() []byte {
	file_weight_proto_rawDescOnce.Do(func() {
		file_weight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weight_proto_rawDesc), len(file_weight_proto_rawDesc)))
	})
	return file_weight_proto_rawDescData
}

var file_weight_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_weight_proto_goTypes = []any{
	(*WeightModel)(nil), // 0: weight.WeightModel
}
var file_weight_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weight_proto_init() }
func file_weight_proto_init() {
	if File_weight_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weight_proto_rawDesc), len(file_weight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weight_proto_goTypes,
		DependencyIndexes: file_weight_proto_depIdxs,
		MessageInfos:      file_weight_proto_msgTypes,
	}.Build()
	File_weight_proto = out.File
	file_weight_proto_goTypes = nil
	file_weight_proto_depIdxs = nil
}
